/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.jinou.habichtescouting.server.api;

import io.swagger.annotations.*;
import io.swagger.model.Spieler;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.constraints.*;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-20T16:25:36.526Z")

@Api(value = "neuespieler", description = "the neuespieler API")
public interface NeuespielerApi {

    @ApiOperation(value = "Zeigt neu angelegte Spieler", nickname = "neuespielerGet", notes = "", response = Spieler.class, tags={ "neuespieler", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Spieler.class),
        @ApiResponse(code = 400, message = "Invalid Order") })
    @RequestMapping(value = "/neuespieler",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Spieler> neuespielerGet();

}
