/**
 * Habicht Scouting
 * Api fuer Habicht Scouting.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@jinou.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.jinou.habichtescouting.app.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.*;

@ApiModel(description = "")
public class Scout {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("password")
  private String password = null;
  @SerializedName("userStatus")
  private Integer userStatus = null;
  @SerializedName("zuletztOnline")
  private Long zuletztOnline = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * User Status
   **/
  @ApiModelProperty(value = "User Status")
  public Integer getUserStatus() {
    return userStatus;
  }
  public void setUserStatus(Integer userStatus) {
    this.userStatus = userStatus;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getZuletztOnline() {
    return zuletztOnline;
  }
  public void setZuletztOnline(Long zuletztOnline) {
    this.zuletztOnline = zuletztOnline;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Scout scout = (Scout) o;
    return (this.id == null ? scout.id == null : this.id.equals(scout.id)) &&
        (this.email == null ? scout.email == null : this.email.equals(scout.email)) &&
        (this.password == null ? scout.password == null : this.password.equals(scout.password)) &&
        (this.userStatus == null ? scout.userStatus == null : this.userStatus.equals(scout.userStatus)) &&
        (this.zuletztOnline == null ? scout.zuletztOnline == null : this.zuletztOnline.equals(scout.zuletztOnline));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    result = 31 * result + (this.userStatus == null ? 0: this.userStatus.hashCode());
    result = 31 * result + (this.zuletztOnline == null ? 0: this.zuletztOnline.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Scout {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("  userStatus: ").append(userStatus).append("\n");
    sb.append("  zuletztOnline: ").append(zuletztOnline).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
