/**
 * Habicht Scouting
 * Api fuer Habicht Scouting.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@jinou.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.jinou.habichtescouting.app.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.*;

@ApiModel(description = "")
public class Spieler {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("spielernummer")
  private Long spielernummer = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("position")
  private String position = null;
  @SerializedName("verein")
  private String verein = null;
  @SerializedName("beschreibung")
  private String beschreibung = null;
  @SerializedName("angelegtAm")
  private Long angelegtAm = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getSpielernummer() {
    return spielernummer;
  }
  public void setSpielernummer(Long spielernummer) {
    this.spielernummer = spielernummer;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPosition() {
    return position;
  }
  public void setPosition(String position) {
    this.position = position;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVerein() {
    return verein;
  }
  public void setVerein(String verein) {
    this.verein = verein;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBeschreibung() {
    return beschreibung;
  }
  public void setBeschreibung(String beschreibung) {
    this.beschreibung = beschreibung;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getAngelegtAm() {
    return angelegtAm;
  }
  public void setAngelegtAm(Long angelegtAm) {
    this.angelegtAm = angelegtAm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Spieler spieler = (Spieler) o;
    return (this.id == null ? spieler.id == null : this.id.equals(spieler.id)) &&
        (this.spielernummer == null ? spieler.spielernummer == null : this.spielernummer.equals(spieler.spielernummer)) &&
        (this.name == null ? spieler.name == null : this.name.equals(spieler.name)) &&
        (this.position == null ? spieler.position == null : this.position.equals(spieler.position)) &&
        (this.verein == null ? spieler.verein == null : this.verein.equals(spieler.verein)) &&
        (this.beschreibung == null ? spieler.beschreibung == null : this.beschreibung.equals(spieler.beschreibung)) &&
        (this.angelegtAm == null ? spieler.angelegtAm == null : this.angelegtAm.equals(spieler.angelegtAm));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.spielernummer == null ? 0: this.spielernummer.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.position == null ? 0: this.position.hashCode());
    result = 31 * result + (this.verein == null ? 0: this.verein.hashCode());
    result = 31 * result + (this.beschreibung == null ? 0: this.beschreibung.hashCode());
    result = 31 * result + (this.angelegtAm == null ? 0: this.angelegtAm.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Spieler {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  spielernummer: ").append(spielernummer).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  position: ").append(position).append("\n");
    sb.append("  verein: ").append(verein).append("\n");
    sb.append("  beschreibung: ").append(beschreibung).append("\n");
    sb.append("  angelegtAm: ").append(angelegtAm).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
